/// Locale-independent UI message. Resolve it in the presentation layer.
/// [detail] is user content (a device, file item or tournament name), not prose.
class AppMessage {
  final AppMessageId id;
  final String? detail;
  const AppMessage(this.id, {this.detail});

  @override
  bool operator ==(Object other) =>
      other is AppMessage && other.id == id && other.detail == detail;

  @override
  int get hashCode => Object.hash(id, detail);
}

enum AppMessageId {
  unexpectedError,
  packageTooFewItems,
  packageTooManyItems,
  packageImageTooLarge,
  packageImageMissing,
  packageResourceTooLarge,
  packageCreateFailed,
  packageMissing,
  packageTooLarge,
  packageInvalid,
  packageDuplicateResource,
  packageManifestMissing,
  packageManifestUnreadable,
  packageUnsafePath,
  packageDuplicateImage,
  packageImageDamaged,
  packageImageUnreadable,
  packageImportFailed,
  packageUnsupported,
  packageManifestDamaged,
  packageItemDamaged,
  packageIncomplete,
  supportConfiguration,
  supportAddress,
  supportNetwork,
  supportEmailInvalid,
  supportContentInvalid,
  supportScreenshotInvalid,
  supportValidation,
  supportAuthentication,
  supportNotFound,
  supportThrottled,
  supportServer,
  supportInvalidResponse,
  supportNoticesResponse,
  supportReceiptResponse,
  supportImageConfiguration,
  supportImageUpload,
  supportImageResponse,
  supportNoticesFailed,
  supportContentRequired,
  supportContentTooLong,
  supportImageSize,
  supportImageSelection,
  supportImageEmpty,
  supportInquiryFailed,
  nearbyPreparing,
  nearbyDiscovering,
  nearbyDiscoveryTimeout,
  nearbyReady,
  nearbyRequestingConnection,
  nearbyConnectionTimeout,
  nearbyWaitingForPeer,
  nearbyVerificationTimeout,
  nearbyRejectedLocally,
  nearbySendCanceled,
  nearbyReceiveCanceled,
  nearbyPreparingCode,
  nearbyVerifyCode,
  nearbySecuringConnection,
  nearbyConnected,
  nearbyReceiveTimeout,
  nearbyRejectedByPeer,
  nearbyFinalizingDisconnected,
  nearbyFinalizationTimeout,
  nearbyDisconnected,
  nearbySending,
  nearbyReceiving,
  nearbySendTimeout,
  nearbySendSuccess,
  nearbyCheckingFile,
  nearbyTransferCanceled,
  nearbyTransferFailed,
  nearbyCreatingFile,
  nearbyPreparationTimeout,
  nearbyImporting,
  nearbyReceiveSuccess,
  nearbyUnsupported,
  nearbyPermissionBlocked,
  nearbyPermissionRequired,
  nearbyRadiosDisabled,
  nearbyStartFailed,
  nearbyImportFailed,
  nearbyError,
}
